In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('hospital_dataset_20000_messy.csv')

pd.set_option('Display.max_rows', None)
pd.set_option('Display.max_columns', None)

df.head()

,patient_id,patient_name,age,gender,blood_type,city,state,admission_date,discharge_date,length_of_stay_days,admission_type,department,diagnosis,attending_doctor,bed_type,heart_rate,systolic_bp,diastolic_bp,temperature_f,insurance_provider,billing_amount_usd,payment_status,outcome,readmitted_30_days,patient_satisfaction_score
0,PT103031,Steven Hernandez,90.0,Male,A-,Jacksonville,FL,2023-07-05,2023-07-12,7,Urgent,Neurology,Stroke,Dr. Kelly,General Ward,76,102.0,85.0,99.6,CIGNA,7562.93,Insurance Processing,Transferred,TRUE,3.0
1,PT111091,Anthony Gomez,26.0,Male,O+,Detroit,MI,2025-10-23,2025-10-30,7,Emergency,Neurologyy,Concussion,Dr. Howard,Private Room,106,131.0,100.0,100.8,MEDICARE,11154.31,Paid,Left Against Medical Advice,Yes,NaN
2,PT107264,Michael Parker,8.0,Female,O+,San Francisco,CA,10/03/24,10/06/2024,3,Elective,Pediatrics,Croup,Dr. Morgan,General Ward,102,101.0,98.0,100.0,Kaiser Permanente,3928.4,Paid,Discharged - Recovered,Yes,4.0
3,PT106342,Debra Stewart,16.0,Male,A+,Las Vegas,NV,09/23/2022,25-09-2022,2,Newborn,Derm,Eczema,Dr. Baker,Semi-Private,79,NaN,63.0,NaN,BCBS,4346.07,Insurance Processing,Discharged - Recovered,No,4.0
4,PT102136,William Garcia,79.0,Male,O-,Philadelphia,PA,2024-08-13,08/19/24,6,Urgent,Neurology,Epilepsy,Dr. Martinez,NICU,60,105.0,91.0,100.5,NaN,34667.52,Partially Paid,Discharged - Recovered,no,5.0

In [4]:
df.shape

(20400, 25)

In [5]:
df.columns

Index(['patient_id', 'patient_name', 'age', 'gender', 'blood_type', 'city',
       'state', 'admission_date', 'discharge_date', 'length_of_stay_days',
       'admission_type', 'department', 'diagnosis', 'attending_doctor',
       'bed_type', 'heart_rate', 'systolic_bp', 'diastolic_bp',
       'temperature_f', 'insurance_provider', 'billing_amount_usd',
       'payment_status', 'outcome', 'readmitted_30_days',
       'patient_satisfaction_score'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20400 entries, 0 to 20399
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   patient_id                  20400 non-null  str
 1   patient_name                20190 non-null  str
 2   age                         19998 non-null  float64
 3   gender                      20068 non-null  str
 4   blood_type                  18788 non-null  str
 5   city                        20400 non-null  str
 6   state                       20400 non-null  str
 7   admission_date              20400 non-null  str
 8   discharge_date              20209 non-null  str
 9   length_of_stay_days         20400 non-null  int64
 10  admission_type              20400 non-null  str
 11  department                  20400 non-null  str
 12  diagnosis                   20378 non-null  str
 13  attending_doctor            20079 non-null  str
 14  bed_type                    20400 non-null  str
 15  heart_rate                  19802 non-null  str
 16  systolic_bp                 19783 non-null  float64
 17  diastolic_bp                19790 non-null  float64
 18  temperature_f               19804 non-null  str
 19  insurance_provider          19755 non-null  str
 20  billing_amount_usd          20400 non-null  str
 21  payment_status              19950 non-null  str
 22  outcome                     20400 non-null  str
 23  readmitted_30_days          19966 non-null  str
 24  patient_satisfaction_score  17974 non-null  float64
dtypes: float64(4), int64(1), str(20)
memory usage: 3.9 MB

In [8]:
df.describe(include = 'all')

,patient_id,patient_name,age,gender,blood_type,city,state,admission_date,discharge_date,length_of_stay_days,admission_type,department,diagnosis,attending_doctor,bed_type,heart_rate,systolic_bp,diastolic_bp,temperature_f,insurance_provider,billing_amount_usd,payment_status,outcome,readmitted_30_days,patient_satisfaction_score
count,20400,20190,19998.000000,20068,18788,20400,20400,20400,20209,20400.000000,20400,20400,20378,20079,20400,19802,19783.000000,19790.000000,19804,19755,20400,19950,20400,19966,17974.000000
unique,20100,9833,NaN,10,8,37,42,5816,5786,NaN,4,56,84,118,6,106,NaN,NaN,92,33,19877,7,5,12,NaN
top,PT113816,Sandra Howard,NaN,Female,O+,Louisville,TX,2024-10-08,2025-09-17,NaN,Emergency,Psychiatry,Kidney Stones,Dr. Lewis,NICU,76,NaN,NaN,98.7,Humana,2383.69,Paid,Discharged - Recovered,No,NaN
freq,2,9,NaN,7343,7459,742,3054,19,19,NaN,5879,1064,619,676,3466,419,NaN,NaN,478,1584,3,9020,11238,12655,NaN
mean,NaN,NaN,44.399890,NaN,NaN,NaN,NaN,NaN,NaN,3.568088,NaN,NaN,NaN,NaN,NaN,NaN,130.260577,79.952097,NaN,NaN,NaN,NaN,NaN,NaN,3.944253
std,NaN,NaN,39.983749,NaN,NaN,NaN,NaN,NaN,NaN,2.378365,NaN,NaN,NaN,NaN,NaN,NaN,20.562669,11.766962,NaN,NaN,NaN,NaN,NaN,NaN,0.900433
min,NaN,NaN,-5.000000,NaN,NaN,NaN,NaN,NaN,NaN,-13.000000,NaN,NaN,NaN,NaN,NaN,NaN,95.000000,60.000000,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000
25%,NaN,NaN,23.000000,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,NaN,NaN,NaN,112.000000,70.000000,NaN,NaN,NaN,NaN,NaN,NaN,3.000000
50%,NaN,NaN,41.000000,NaN,NaN,NaN,NaN,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,NaN,NaN,130.000000,80.000000,NaN,NaN,NaN,NaN,NaN,NaN,4.000000
75%,NaN,NaN,62.000000,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,NaN,NaN,148.000000,90.000000,NaN,NaN,NaN,NaN,NaN,NaN,5.000000
max,NaN,NaN,999.000000,NaN,NaN,NaN,NaN,NaN,NaN,16.000000,NaN,NaN,NaN,NaN,NaN,NaN,165.000000,100.000000,NaN,NaN,NaN,NaN,NaN,NaN,10.000000

In [9]:
df.isnull().sum()

patient_id                       0
patient_name                   210
age                            402
gender                         332
blood_type                    1612
city                             0
state                            0
admission_date                   0
discharge_date                 191
length_of_stay_days              0
admission_type                   0
department                       0
diagnosis                       22
attending_doctor               321
bed_type                         0
heart_rate                     598
systolic_bp                    617
diastolic_bp                   610
temperature_f                  596
insurance_provider             645
billing_amount_usd               0
payment_status                 450
outcome                          0
readmitted_30_days             434
patient_satisfaction_score    2426
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(300)

In [15]:
duplicates = df.duplicated()

In [16]:
duplicates.head()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [17]:
df.columns.tolist()

['patient_id',
 'patient_name',
 'age',
 'gender',
 'blood_type',
 'city',
 'state',
 'admission_date',
 'discharge_date',
 'length_of_stay_days',
 'admission_type',
 'department',
 'diagnosis',
 'attending_doctor',
 'bed_type',
 'heart_rate',
 'systolic_bp',
 'diastolic_bp',
 'temperature_f',
 'insurance_provider',
 'billing_amount_usd',
 'payment_status',
 'outcome',
 'readmitted_30_days',
 'patient_satisfaction_score']

In [19]:
# Basic structure after duplicate removal
print("Rows:", len(df))
print("Unique Patient IDs:", df["patient_id"].nunique())
print("Duplicate Patient IDs:", df["patient_id"].duplicated().sum())

Rows: 20400
Unique Patient IDs: 20100
Duplicate Patient IDs: 300

In [20]:
df['age'].describe()

count    19998.000000
mean        44.399890
std         39.983749
min         -5.000000
25%         23.000000
50%         41.000000
75%         62.000000
max        999.000000
Name: age, dtype: float64